# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: android_env/proto/a11y/a11y.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'android_env/proto/a11y/a11y.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from android_env.proto.a11y import android_accessibility_forest_pb2 as android__env_dot_proto_dot_a11y_dot_android__accessibility__forest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!android_env/proto/a11y/a11y.proto\x12\x0b\x61ndroid_env\x1a\x39\x61ndroid_env/proto/a11y/android_accessibility_forest.proto\"k\n\tA11yEvent\x12\x30\n\x05\x65vent\x18\x01 \x03(\x0b\x32!.android_env.A11yEvent.EventEntry\x1a,\n\nEventEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x0e\x43lientToServer\x12\'\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x16.android_env.A11yEventH\x00\x12\x39\n\x06\x66orest\x18\x02 \x01(\x0b\x32\'.android_env.AndroidAccessibilityForestH\x00\x42\t\n\x07payload\"m\n\x0eServerToClient\x12?\n\nget_forest\x18\x01 \x01(\x0b\x32).android_env.ServerToClient.GetA11yForestH\x00\x1a\x0f\n\rGetA11yForestB\t\n\x07payload2U\n\x0b\x41\x31\x31yService\x12\x46\n\x04\x42idi\x12\x1b.android_env.ClientToServer\x1a\x1b.android_env.ServerToClient\"\x00(\x01\x30\x01\x42\x30\n,com.google.androidenv.accessibilityforwarderP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'android_env.proto.a11y.a11y_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n,com.google.androidenv.accessibilityforwarderP\001'
  _globals['_A11YEVENT_EVENTENTRY']._loaded_options = None
  _globals['_A11YEVENT_EVENTENTRY']._serialized_options = b'8\001'
  _globals['_A11YEVENT']._serialized_start=109
  _globals['_A11YEVENT']._serialized_end=216
  _globals['_A11YEVENT_EVENTENTRY']._serialized_start=172
  _globals['_A11YEVENT_EVENTENTRY']._serialized_end=216
  _globals['_CLIENTTOSERVER']._serialized_start=218
  _globals['_CLIENTTOSERVER']._serialized_end=345
  _globals['_SERVERTOCLIENT']._serialized_start=347
  _globals['_SERVERTOCLIENT']._serialized_end=456
  _globals['_SERVERTOCLIENT_GETA11YFOREST']._serialized_start=430
  _globals['_SERVERTOCLIENT_GETA11YFOREST']._serialized_end=445
  _globals['_A11YSERVICE']._serialized_start=458
  _globals['_A11YSERVICE']._serialized_end=543
# @@protoc_insertion_point(module_scope)
